export const REGIONS = [
  { id: 'sumatra', name: 'Sumatra', color: '#f3b562', note: 'Aceh, Minangkabau, Batak, Malay worlds, and Lake Toba.' },
  { id: 'java', name: 'Java', color: '#e77f67', note: 'The most populous island: courts, pesantren, cities, volcanoes, and rice landscapes.' },
  { id: 'kalimantan', name: 'Kalimantan', color: '#5aa9a1', note: 'Rainforest, rivers, Dayak societies, mining, and the new capital region.' },
  { id: 'sulawesi', name: 'Sulawesi', color: '#7f8cda', note: 'Bugis-Makassar seafaring, Toraja traditions, and unusual island geography.' },
  { id: 'bali-nusa', name: 'Bali & Nusa Tenggara', color: '#d95d81', note: 'Balinese Hindu culture, dry islands, weaving, and eastern archipelago routes.' },
  { id: 'maluku', name: 'Maluku', color: '#74b49b', note: 'The Spice Islands: cloves, nutmeg, sultanates, and global competition.' },
  { id: 'papua', name: 'Papua', color: '#557571', note: 'A vast eastern region with extraordinary cultural and ecological diversity.' },
];

export const LESSONS = [
  {
    id: 'what-is-indonesia',
    number: 1,
    region: 'All Indonesia',
    title: 'What actually is Indonesia?',
    subtitle: 'A country made from islands, seas, and many societies',
    outcome: 'Explain why Indonesia is both a connected nation and a collection of distinct local worlds.',
    duration: '12 min',
    xp: 100,
    tag: 'Foundation',
    color: '#0d5c56',
    facts: [
      ['Established', 'Indonesia is an archipelagic state stretching between the Indian and Pacific Oceans.'],
      ['Established', 'The national identity is shared, but local identities remain powerful and meaningful.'],
      ['Interpretation', 'Indonesia makes more sense as many societies gradually connected into one political nation—not as one uniform culture.'],
    ],
    story: 'Think of Indonesia less as a single block of land and more as a chain of worlds connected by water. Trade, migration, religion, and later nationalism tied those worlds together.',
    sections: [
      {
        title: 'Start with the shape of the country',
        purpose: 'Build the mental map',
        reading: 'Indonesia is an archipelago: a country made up of thousands of islands spread between the Indian and Pacific Oceans. That geography matters because people historically moved through ports, straits, rivers, and coastal settlements rather than across one continuous mainland.',
        question: 'What does “archipelago” help you notice about Indonesia?',
        answers: ['It is one continuous landmass', 'It is a country made up of many islands connected by sea routes', 'It has no important cities', 'It is divided into separate countries'],
        correct: 1,
      },
      {
        title: 'See connection, not isolation',
        purpose: 'Understand how the islands relate',
        reading: 'Water separated communities, but it also connected them. Sailors, merchants, pilgrims, migrants, and ideas crossed the seas. A port could connect a local society to other islands, India, China, Arabia, and Southeast Asia.',
        question: 'Why should we not treat the sea only as a barrier?',
        answers: ['Because sea routes also carried people, goods, and ideas', 'Because every island had the same culture', 'Because nobody lived near the coast', 'Because mountains made travel easy'],
        correct: 0,
      },
      {
        title: 'Hold two ideas at once',
        purpose: 'Use the idea to interpret real life',
        reading: 'Indonesia has a shared national identity, but it is not one uniform culture. A person can be Indonesian nationally while also identifying with a local language, island, ethnic community, religion, city, or customary tradition. The useful starting point is layered belonging.',
        question: 'What is the most useful way to understand Indonesian identity?',
        answers: ['As one uniform culture', 'As layered identities within a shared nation', 'As identities with no connection to place', 'As something determined only by language'],
        correct: 1,
      },
    ],
    vocabulary: [['nusantara', 'the archipelago / Indonesian world'], ['pulau', 'island'], ['laut', 'sea'], ['masyarakat', 'society or community'], ['beragam', 'diverse']],
    question: 'What is the most useful starting idea for understanding Indonesia?',
    answers: ['It is one uniform culture', 'It is an archipelago of many societies that became one nation', 'It is mainly defined by Java', 'It is a recent invented country with no older connections'],
    correct: 1,
  },
  {
    id: 'map-of-indonesia',
    number: 2,
    region: 'Geography',
    title: 'Read the map before the history',
    subtitle: 'Islands, volcanoes, monsoons, and maritime routes',
    outcome: 'Use geography to explain why settlement, trade, and regional importance developed unevenly across Indonesia.',
    duration: '15 min',
    xp: 100,
    tag: 'Geography',
    color: '#236b8e',
    facts: [
      ['Established', 'Indonesia is usually learned through seven broad island regions: Sumatra, Java, Kalimantan, Sulawesi, Bali/Nusa Tenggara, Maluku, and Papua.'],
      ['Established', 'The sea was a connector as much as a barrier; many communities were oriented toward coasts, rivers, and shipping routes.'],
      ['Likely', 'Volcanic soils, monsoon cycles, and unequal access to ports helped produce major regional differences.'],
    ],
    story: 'A map explains why Java became densely settled, why Maluku became globally important for spices, and why seafaring communities such as the Bugis built far-reaching networks.',
    sections: [
      {
        title: 'Why Java became densely settled',
        purpose: 'Read population through geography',
        reading: 'Java is one of the world’s most densely populated islands partly because volcanic soils support intensive agriculture, while mountains, rivers, and relatively reliable rainfall created productive farming zones. Over centuries, courts, villages, roads, and cities accumulated in the same limited space.',
        question: 'Which combination best helps explain Java’s dense settlement?',
        answers: ['Volcanic soils and productive farming zones', 'A complete lack of mountains', 'Its distance from all trade routes', 'Its dry climate and empty interior'],
        correct: 0,
      },
      {
        title: 'Why maritime routes mattered',
        purpose: 'See the sea as infrastructure',
        reading: 'For an island country, the sea is part of the transport system. Straits and ports connected producers, sailors, merchants, and political centers. Monsoon winds also shaped when ships could travel, making seasonal knowledge an important form of geographic expertise.',
        question: 'What made maritime routes historically valuable?',
        answers: ['They connected coasts through ports, straits, and seasonal sailing patterns', 'They made every island politically identical', 'They stopped people from migrating', 'They removed the need for local agriculture'],
        correct: 0,
      },
      {
        title: 'Why Maluku became globally important',
        purpose: 'Connect geography to world history',
        reading: 'The Maluku Islands were famous for cloves and nutmeg. These products were valuable far beyond the islands, so local ports and sultanates became entangled in wider Asian and European competition. A small region could have an outsized historical importance when it controlled a desired resource.',
        question: 'Why did Maluku matter far beyond its size?',
        answers: ['It controlled access to highly valued spices', 'It had the largest population in Indonesia', 'It was the only place with volcanoes', 'It was isolated from international trade'],
        correct: 0,
      },
    ],
    vocabulary: [['gunung berapi', 'volcano'], ['selat', 'strait'], ['pesisir', 'coast'], ['kepulauan', 'archipelago'], ['wilayah', 'region']],
    question: 'Why was the sea so important to Indonesian history?',
    answers: ['It isolated every community completely', 'It connected communities through trade and travel', 'It prevented migration', 'It made agriculture impossible'],
    correct: 1,
  },
  {
    id: 'peoples-and-languages',
    number: 3,
    region: 'People & culture',
    title: 'Peoples, languages, and belonging',
    subtitle: 'Javanese, Sundanese, Minangkabau, Batak, Bugis, Papuan groups, and more',
    outcome: 'Distinguish nationality, ethnicity, language, religion, and region without treating them as the same thing.',
    duration: '16 min',
    xp: 100,
    tag: 'People',
    color: '#a44a3f',
    facts: [
      ['Established', 'Indonesia contains hundreds of ethnic and language communities.'],
      ['Established', 'Bahasa Indonesia functions as a shared national language alongside local languages.'],
      ['Important caution', 'Ethnicity, language, religion, province, and nationality are related but not interchangeable categories.'],
    ],
    story: 'A person can be Indonesian nationally, Javanese or Sundanese ethnically, Muslim or Christian religiously, and speak Bahasa Indonesia plus a local language. Identity is layered.',
    sections: [
      {
        title: 'Diversity is organized, not random',
        purpose: 'Name the kinds of difference',
        reading: 'Indonesia contains hundreds of ethnic and language communities. These differences are connected to histories of migration, settlement, trade, kingdoms, colonial administration, and local environments. Diversity is not just a list of groups; it is the result of many social histories meeting across an archipelago.',
        question: 'What is one reason Indonesia has so many communities and languages?',
        answers: ['Long histories of migration, settlement, and regional exchange', 'Because every community was created recently', 'Because the country has only one island', 'Because local languages were never used'],
        correct: 0,
      },
      {
        title: 'Why Bahasa Indonesia matters',
        purpose: 'Understand the shared national language',
        reading: 'Bahasa Indonesia gives people from different language communities a shared public language. It is used in education, government, media, and national communication, while local languages continue to matter in families and communities. A shared language can connect people without erasing every local language.',
        question: 'What role does Bahasa Indonesia mainly play?',
        answers: ['A shared national language alongside local languages', 'A replacement for all local languages', 'A language spoken only in Java', 'A religious language used only in ceremonies'],
        correct: 0,
      },
      {
        title: 'Identity has layers',
        purpose: 'Avoid flattening people into one label',
        reading: 'A person can be Indonesian by nationality, Javanese by ethnic identity, Muslim by religion, from Bandung by city, and fluent in both Bahasa Indonesia and Sundanese. These labels answer different questions. Treating them as interchangeable makes real people and communities harder to understand.',
        question: 'Why is it important to keep identity categories distinct?',
        answers: ['They describe different parts of a person’s belonging', 'Only nationality is real', 'Religion always determines language', 'A person can have only one identity'],
        correct: 0,
      },
    ],
    vocabulary: [['suku', 'ethnic group'], ['bahasa daerah', 'local language'], ['identitas', 'identity'], ['orang', 'person or people'], ['bangsa', 'nation or people']],
    question: 'What does Bahasa Indonesia mainly provide?',
    answers: ['A replacement for every local language', 'A shared national language across diverse communities', 'A language spoken only in Java', 'A religious language'],
    correct: 1,
  },
  {
    id: 'trade-and-kingdoms',
    number: 4,
    region: 'History',
    title: 'Trade, kingdoms, and the maritime world',
    subtitle: 'Srivijaya, Majapahit, and networks before the modern state',
    outcome: 'Explain how ports, trade, religion, and political power connected the archipelago before the modern republic.',
    duration: '18 min',
    xp: 100,
    tag: 'History',
    color: '#9b6a3c',
    facts: [
      ['Established', 'The archipelago participated in wider networks involving India, China, Arabia, and Southeast Asia.'],
      ['Established', 'Srivijaya was a major maritime power connected to the Strait of Malacca.'],
      ['Simplified', 'Majapahit is important to Indonesian historical imagination, but its actual political influence was not identical to the borders of modern Indonesia.'],
    ],
    story: 'Before Indonesia existed as a republic, ports, courts, trading communities, and religious centers linked the islands into overlapping worlds.',
    sections: [
      {
        title: 'Ports made the archipelago legible',
        purpose: 'See where exchange happened',
        reading: 'Ports were places where goods, languages, religious ideas, technologies, and political claims met. They linked inland producers to ships and connected local rulers to wider networks. The history of the archipelago is therefore not only the history of capitals; it is also the history of coastal exchange.',
        question: 'Why were ports important beyond simply loading ships?',
        answers: ['They brought together goods, people, ideas, and political relationships', 'They prevented cultural exchange', 'They existed only after independence', 'They made inland communities irrelevant'],
        correct: 0,
      },
      {
        title: 'Srivijaya and the Strait of Malacca',
        purpose: 'Understand maritime power',
        reading: 'Srivijaya became influential by operating in a strategic maritime zone around the Strait of Malacca. Its power depended on relationships with ports, shipping routes, and regional trade rather than on controlling every island directly. Maritime states could be powerful through networks.',
        question: 'What kind of power helped Srivijaya become influential?',
        answers: ['Control and influence over maritime routes and port networks', 'A centralized government over modern Indonesia’s exact borders', 'Isolation from international trade', 'Control of all inland farming villages'],
        correct: 0,
      },
      {
        title: 'Majapahit and historical memory',
        purpose: 'Separate memory from exact borders',
        reading: 'Majapahit is important in Indonesian historical imagination, especially as a symbol of earlier political and cultural connections. But its historical influence was not identical to the borders of the modern republic. Studying the past well means respecting both what a kingdom did and how later generations remember it.',
        question: 'What is the careful way to discuss Majapahit?',
        answers: ['Recognize its importance without assuming it had modern Indonesia’s exact borders', 'Treat it as identical to the present republic', 'Ignore its role in regional history', 'Assume every story about it is purely fictional'],
        correct: 0,
      },
    ],
    vocabulary: [['kerajaan', 'kingdom'], ['pelabuhan', 'port'], ['dagang', 'trade'], ['rempah-rempah', 'spices'], ['kekuasaan', 'power or authority']],
    question: 'What connected many pre-modern societies in the archipelago?',
    answers: ['Only one centralized government', 'Trade, migration, religious exchange, and regional power networks', 'A single local language', 'European colonial administration'],
    correct: 1,
  },
  {
    id: 'religion-and-adat',
    number: 5,
    region: 'Belief & society',
    title: 'Religion, adat, and everyday life',
    subtitle: 'Beliefs overlapped instead of simply replacing one another',
    outcome: 'Explain how formal religions and local customary traditions shape everyday life together.',
    duration: '15 min',
    xp: 100,
    tag: 'Culture',
    color: '#7b4b94',
    facts: [
      ['Established', 'Islam, Hinduism, Christianity, Buddhism, and local traditions all shape Indonesian life.'],
      ['Established', 'Adat refers broadly to local customary norms and traditions.'],
      ['Likely', 'In many places, formal religion and local custom developed through adaptation and overlap rather than a clean replacement.'],
    ],
    story: 'To understand a wedding, village meeting, funeral, or festival, you often need to see formal religious practice and local adat together.',
    sections: [
      {
        title: 'Religion is part of public and private life',
        purpose: 'Recognize the main traditions',
        reading: 'Islam, Christianity, Hinduism, Buddhism, and local traditions all shape Indonesian life, though their distribution and practice vary by place. Religion can influence celebrations, education, family life, art, law, and community organization. There is no single religious experience that represents every Indonesian.',
        question: 'What is the safest starting point for understanding religion in Indonesia?',
        answers: ['Different traditions shape different communities and places', 'One religion is practiced identically everywhere', 'Religion has no connection to daily life', 'Local traditions disappeared completely'],
        correct: 0,
      },
      {
        title: 'What adat means',
        purpose: 'Learn the local social vocabulary',
        reading: 'Adat refers broadly to customary norms, practices, and traditions. It can shape how communities organize ceremonies, relationships, land, leadership, and conflict resolution. Adat is not one national rulebook; it takes different forms in different places.',
        question: 'What does adat refer to?',
        answers: ['Local customary norms and traditions', 'A single national religion', 'A type of island', 'A colonial tax system'],
        correct: 0,
      },
      {
        title: 'Overlap instead of replacement',
        purpose: 'Interpret everyday practice carefully',
        reading: 'In many communities, formal religious practice and local custom developed through adaptation and overlap. A ceremony may use religious language while also following local forms of music, clothing, food, kinship, or communal responsibility. The important point is not that everything is blended in the same way, but that lived practice is often more layered than categories suggest.',
        question: 'Why should we look at religion and adat together?',
        answers: ['Everyday practice can combine formal belief with local custom', 'They are always exactly the same thing', 'Adat exists only in museums', 'Religion never affects ceremonies'],
        correct: 0,
      },
    ],
    vocabulary: [['adat', 'customary tradition'], ['agama', 'religion'], ['gotong royong', 'communal cooperation'], ['upacara', 'ceremony'], ['kepercayaan', 'belief']],
    question: 'What is adat?',
    answers: ['A single national religion', 'Local customary traditions and norms', 'A type of Indonesian island', 'A colonial tax system'],
    correct: 1,
  },
  {
    id: 'modern-indonesia',
    number: 6,
    region: 'Modern Indonesia',
    title: 'From independence to today',
    subtitle: 'One republic, many regional futures',
    outcome: 'Describe the main political transition from independence through Reformasi and explain why regional differences still matter.',
    duration: '20 min',
    xp: 100,
    tag: 'Modern',
    color: '#cf5c36',
    facts: [
      ['Established', 'Indonesia declared independence in 1945 and fought a subsequent independence struggle.'],
      ['Established', 'The Reformasi period began after the fall of Suharto in 1998.'],
      ['Important caution', 'Modern Indonesia combines national institutions with strong provincial, ethnic, religious, urban, and local identities.'],
    ],
    story: 'The republic is not the end of regional difference. It is the political framework in which those differences continue to negotiate, cooperate, and sometimes conflict.',
    sections: [
      {
        title: 'Independence created a political framework',
        purpose: 'Place 1945 in context',
        reading: 'Indonesia declared independence in 1945 and then fought a difficult struggle to make that declaration real. Independence created a national political framework across a very large and diverse archipelago, but it did not erase the regional histories and inequalities that existed before the republic.',
        question: 'What did independence establish?',
        answers: ['A national political framework that still had to be built and negotiated', 'An immediate end to every regional difference', 'A single culture across all islands', 'A country with no further political conflict'],
        correct: 0,
      },
      {
        title: 'Reformasi changed the political conversation',
        purpose: 'Understand the 1998 turning point',
        reading: 'The Reformasi period began after the fall of Suharto in 1998. It brought major political changes, including more open competition, stronger public debate, and new conversations about decentralization, rights, corruption, and the relationship between the center and the regions.',
        question: 'What does Reformasi refer to in modern Indonesian history?',
        answers: ['A reform period beginning after Suharto’s fall in 1998', 'The first arrival of Islam', 'A pre-modern maritime kingdom', 'A single national festival'],
        correct: 0,
      },
      {
        title: 'One republic, many futures',
        purpose: 'Connect national and regional life',
        reading: 'Modern Indonesia combines national institutions with strong provincial, ethnic, religious, urban, and local identities. Debates about development, natural resources, migration, language, and the new capital are therefore also debates about who benefits, who decides, and how different regions imagine the future.',
        question: 'Why do regional identities still matter today?',
        answers: ['They shape how people experience national decisions and imagine development', 'The republic has no national institutions', 'Regional identities exist only in the past', 'Every province has identical priorities'],
        correct: 0,
      },
    ],
    vocabulary: [['merdeka', 'independent or free'], ['reformasi', 'reform era'], ['negara', 'state or country'], ['provinsi', 'province'], ['masa depan', 'future']],
    question: 'What best describes modern Indonesia?',
    answers: ['A completely centralized culture', 'A national republic containing strong regional identities', 'A group of unrelated countries', 'A society without local traditions'],
    correct: 1,
  },
];
