export const REGIONS = [
  { id: 'sumatra', name: 'Sumatra', color: '#f3b562', note: 'Aceh, Minangkabau, Batak, Malay worlds, and Lake Toba.' },
  { id: 'java', name: 'Java', color: '#e77f67', note: 'The most populous island: courts, pesantren, cities, volcanoes, and rice landscapes.' },
  { id: 'kalimantan', name: 'Kalimantan', color: '#5aa9a1', note: 'Rainforest, rivers, Dayak societies, mining, and the new capital region.' },
  { id: 'sulawesi', name: 'Sulawesi', color: '#7f8cda', note: 'Bugis-Makassar seafaring, Toraja traditions, and unusual island geography.' },
  { id: 'bali-nusa', name: 'Bali & Nusa Tenggara', color: '#d95d81', note: 'Balinese Hindu culture, dry islands, weaving, and eastern archipelago routes.' },
  { id: 'maluku', name: 'Maluku', color: '#74b49b', note: 'The Spice Islands: cloves, nutmeg, sultanates, and global competition.' },
  { id: 'papua', name: 'Papua', color: '#557571', note: 'A vast eastern region with extraordinary cultural and ecological diversity.' },
];

export const LESSONS = [
  {
    id: 'what-is-indonesia',
    number: 1,
    region: 'All Indonesia',
    title: 'What actually is Indonesia?',
    subtitle: 'A country made from islands, seas, and many societies',
    duration: '12 min',
    xp: 100,
    tag: 'Foundation',
    color: '#0d5c56',
    facts: [
      ['Established', 'Indonesia is an archipelagic state stretching between the Indian and Pacific Oceans.'],
      ['Established', 'The national identity is shared, but local identities remain powerful and meaningful.'],
      ['Interpretation', 'Indonesia makes more sense as many societies gradually connected into one political nation—not as one uniform culture.'],
    ],
    story: 'Think of Indonesia less as a single block of land and more as a chain of worlds connected by water. Trade, migration, religion, and later nationalism tied those worlds together.',
    vocabulary: [['nusantara', 'the archipelago / Indonesian world'], ['pulau', 'island'], ['laut', 'sea'], ['masyarakat', 'society or community'], ['beragam', 'diverse']],
    question: 'What is the most useful starting idea for understanding Indonesia?',
    answers: ['It is one uniform culture', 'It is an archipelago of many societies that became one nation', 'It is mainly defined by Java', 'It is a recent invented country with no older connections'],
    correct: 1,
  },
  {
    id: 'map-of-indonesia',
    number: 2,
    region: 'Geography',
    title: 'Read the map before the history',
    subtitle: 'Islands, volcanoes, monsoons, and maritime routes',
    duration: '15 min',
    xp: 100,
    tag: 'Geography',
    color: '#236b8e',
    facts: [
      ['Established', 'Indonesia is usually learned through seven broad island regions: Sumatra, Java, Kalimantan, Sulawesi, Bali/Nusa Tenggara, Maluku, and Papua.'],
      ['Established', 'The sea was a connector as much as a barrier; many communities were oriented toward coasts, rivers, and shipping routes.'],
      ['Likely', 'Volcanic soils, monsoon cycles, and unequal access to ports helped produce major regional differences.'],
    ],
    story: 'A map explains why Java became densely settled, why Maluku became globally important for spices, and why seafaring communities such as the Bugis built far-reaching networks.',
    vocabulary: [['gunung berapi', 'volcano'], ['selat', 'strait'], ['pesisir', 'coast'], ['kepulauan', 'archipelago'], ['wilayah', 'region']],
    question: 'Why was the sea so important to Indonesian history?',
    answers: ['It isolated every community completely', 'It connected communities through trade and travel', 'It prevented migration', 'It made agriculture impossible'],
    correct: 1,
  },
  {
    id: 'peoples-and-languages',
    number: 3,
    region: 'People & culture',
    title: 'Peoples, languages, and belonging',
    subtitle: 'Javanese, Sundanese, Minangkabau, Batak, Bugis, Papuan groups, and more',
    duration: '16 min',
    xp: 100,
    tag: 'People',
    color: '#a44a3f',
    facts: [
      ['Established', 'Indonesia contains hundreds of ethnic and language communities.'],
      ['Established', 'Bahasa Indonesia functions as a shared national language alongside local languages.'],
      ['Important caution', 'Ethnicity, language, religion, province, and nationality are related but not interchangeable categories.'],
    ],
    story: 'A person can be Indonesian nationally, Javanese or Sundanese ethnically, Muslim or Christian religiously, and speak Bahasa Indonesia plus a local language. Identity is layered.',
    vocabulary: [['suku', 'ethnic group'], ['bahasa daerah', 'local language'], ['identitas', 'identity'], ['orang', 'person or people'], ['bangsa', 'nation or people']],
    question: 'What does Bahasa Indonesia mainly provide?',
    answers: ['A replacement for every local language', 'A shared national language across diverse communities', 'A language spoken only in Java', 'A religious language'],
    correct: 1,
  },
  {
    id: 'trade-and-kingdoms',
    number: 4,
    region: 'History',
    title: 'Trade, kingdoms, and the maritime world',
    subtitle: 'Srivijaya, Majapahit, and networks before the modern state',
    duration: '18 min',
    xp: 100,
    tag: 'History',
    color: '#9b6a3c',
    facts: [
      ['Established', 'The archipelago participated in wider networks involving India, China, Arabia, and Southeast Asia.'],
      ['Established', 'Srivijaya was a major maritime power connected to the Strait of Malacca.'],
      ['Simplified', 'Majapahit is important to Indonesian historical imagination, but its actual political influence was not identical to the borders of modern Indonesia.'],
    ],
    story: 'Before Indonesia existed as a republic, ports, courts, trading communities, and religious centers linked the islands into overlapping worlds.',
    vocabulary: [['kerajaan', 'kingdom'], ['pelabuhan', 'port'], ['dagang', 'trade'], ['rempah-rempah', 'spices'], ['kekuasaan', 'power or authority']],
    question: 'What connected many pre-modern societies in the archipelago?',
    answers: ['Only one centralized government', 'Trade, migration, religious exchange, and regional power networks', 'A single local language', 'European colonial administration'],
    correct: 1,
  },
  {
    id: 'religion-and-adat',
    number: 5,
    region: 'Belief & society',
    title: 'Religion, adat, and everyday life',
    subtitle: 'Beliefs overlapped instead of simply replacing one another',
    duration: '15 min',
    xp: 100,
    tag: 'Culture',
    color: '#7b4b94',
    facts: [
      ['Established', 'Islam, Hinduism, Christianity, Buddhism, and local traditions all shape Indonesian life.'],
      ['Established', 'Adat refers broadly to local customary norms and traditions.'],
      ['Likely', 'In many places, formal religion and local custom developed through adaptation and overlap rather than a clean replacement.'],
    ],
    story: 'To understand a wedding, village meeting, funeral, or festival, you often need to see formal religious practice and local adat together.',
    vocabulary: [['adat', 'customary tradition'], ['agama', 'religion'], ['gotong royong', 'communal cooperation'], ['upacara', 'ceremony'], ['kepercayaan', 'belief']],
    question: 'What is adat?',
    answers: ['A single national religion', 'Local customary traditions and norms', 'A type of Indonesian island', 'A colonial tax system'],
    correct: 1,
  },
  {
    id: 'modern-indonesia',
    number: 6,
    region: 'Modern Indonesia',
    title: 'From independence to today',
    subtitle: 'One republic, many regional futures',
    duration: '20 min',
    xp: 100,
    tag: 'Modern',
    color: '#cf5c36',
    facts: [
      ['Established', 'Indonesia declared independence in 1945 and fought a subsequent independence struggle.'],
      ['Established', 'The Reformasi period began after the fall of Suharto in 1998.'],
      ['Important caution', 'Modern Indonesia combines national institutions with strong provincial, ethnic, religious, urban, and local identities.'],
    ],
    story: 'The republic is not the end of regional difference. It is the political framework in which those differences continue to negotiate, cooperate, and sometimes conflict.',
    vocabulary: [['merdeka', 'independent or free'], ['reformasi', 'reform era'], ['negara', 'state or country'], ['provinsi', 'province'], ['masa depan', 'future']],
    question: 'What best describes modern Indonesia?',
    answers: ['A completely centralized culture', 'A national republic containing strong regional identities', 'A group of unrelated countries', 'A society without local traditions'],
    correct: 1,
  },
];
